apiVersion: v1
kind: Service
metadata:
  name: model-service
  labels:
    app: model
spec:
  selector:
    app: model
  ports:
    - name: model
      protocol: TCP
      port: 80
      targetPort: 80
