name: Python tests

on:
  push:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r service/requirements.txt
      - name: Check PEP8 compliance
        run: |
          black --check --verbose service
      - name: Lint with mypy
        run: |
          mypy --ignore-missing-imports service
      - name: Unit Integration tests with pytest
        run: |
          pytest